name: Extract LocateIds and Call API

# Trigger the workflow on pushes to the main branch
on:
  push:
    branches:
      - main

jobs:
  extract-and-call-api:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run the extraction and API call script
      - name: Extract LocateIds and Call API
        env:
          API_KEY: ${{ secrets.API_KEY }}  # Only if your API requires a key
        run: |
          python extract_and_call_api.py

      # Step 5: Commit and push generated Markdown files
      - name: Commit and Push Changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Add LocateId Markdown files from API responses"
          # Optionally specify the directory if you're using one
          paths: |
             api_responses/*.md
